export type Product = {
  id: number,
  name: string,
  subcategorieRus: string,
  subcategorie: string,
  categorie: string,
  skinType: string[],
  description: string,
  compound: string,
  howToUse: string,
  price: number,
  volume: string,
  isBestSeller: boolean,
  isSPF: boolean,
  previewImage: string,
  image: string,
};
